-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = $HOME/.config/hypr/animations/default.conf -> requires manual conversion
-- local default = require("default")
-- TODO: convert $HOME/.config/hypr/animations/default.conf to .lua and use require()
