-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Source Files

local monitors = require("monitors")
local startup = require("startup")
local inputs = require("inputs")
local keybinds = require("keybinds")
local windowrules = require("windowrules")
local animations = require("animations")
local theme = require("themes.theme")
local workspaces = require("workspaces")

-- Layouts

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
hl.config({
    dwindle = {
        preserve_split = true,
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/
hl.config({
    master = {
        new_status = "master",
    },
})

-- Misc

-- See https://wiki.hyprland.org/Configuring/Variables/#misc
hl.config({
    misc = {
        vrr = 0,
        -- 0=OFF 1=ON 2=FULLSCREEN ONLY
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        anr_missed_pings = 5,
        allow_session_lock_restore = true,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.config({
    general = {
        snap = {
            -- snapping for floating windows
            enabled = true,
        },
    },
})

-- Load Custom Noctalia Colors
require("noctalia.noctalia-colors")
