-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--Keybinds

local scrPath = "local_var_HOME/.config/hypr/Scripts"

local mainMod = "SUPER"

-- 1. Applications

local TERMINAL = "kitty"

local EDITOR = "code"

local EXPLORER = "thunar"

local BROWSER = "~/.config/hypr/Scripts/browser-launcher.sh"

hl.bind("SUPER" .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

--"Terminal"

hl.bind("SUPER" .. " + " .. "E", hl.dsp.exec_cmd("thunar"))

--"File Manager"

hl.bind("SUPER" .. " + " .. "C", hl.dsp.exec_cmd("code"))

--"VS Code"

hl.bind("SUPER" .. " + " .. "B", hl.dsp.exec_cmd("~/.config/hypr/Scripts/browser-launcher.sh"))

--"Browser"

hl.bind("SUPER" .. " + " .. "Z", hl.dsp.exec_cmd("zapzap"))

--"zapzap"

--2. Noctalia

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))

--"Launcher"

hl.bind("SUPER" .. " + " .. "L", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call lockScreen lock"))

--"Lockscreen"

hl.bind("SUPER" .. " + " .. "T", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call settings toggle"))

--"Settings"

hl.bind("SUPER" .. " + " .. "O", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call controlCenter toggle"))

--"Control Center"

hl.bind("SUPER" .. " + " .. "H", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call plugin:keybind-cheatsheet toggle"))

--"Keyhints Cheatsheet"

hl.bind("SUPER" .. " + " .. "K", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call plugin:hyprland-keybinds toggle"))

--"Keybind Editor"

-- 3. Window Management

hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())

--"Close Windows"

hl.bind("SUPER" .. " + " .. "W", hl.dsp.window.float())

--"Toggle Floating"

hl.bind("SUPER" .. " + " .. "J", hl.dsp.layout("togglesplit"))

--"Toggle Split Direction"

hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

--"Toggle Fullscreen"

hl.bind("SUPER" .. " + " .. "tab", hl.dsp.focus({ workspace = "m+1" }))

--"Workspace Up"

hl.bind("SUPER + SHIFT" .. " + " .. "tab", hl.dsp.focus({ workspace = "m-1" }))

--"Workspace Down"

hl.bind("SUPER" .. " + " .. "Left", hl.dsp.focus({ direction = "left" }))

--"Focus Left"

hl.bind("SUPER" .. " + " .. "Right", hl.dsp.focus({ direction = "right" }))

--"Focus Right"

hl.bind("SUPER" .. " + " .. "Up", hl.dsp.focus({ direction = "up" }))

--"Focus Up"

hl.bind("SUPER" .. " + " .. "Down", hl.dsp.focus({ direction = "down" }))

--"Focus Down"

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

--"Cycle Focus"

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("SUPER + SHIFT + Right", hl.dsp.resizeactive("30 0"))

--"Resize Right"

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("SUPER + SHIFT + Left", hl.dsp.resizeactive("-30 0"))

--"Resize Left"

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("SUPER + SHIFT + Up", hl.dsp.resizeactive("0 -30"))

--"Resize Up"

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("SUPER + SHIFT + Down", hl.dsp.resizeactive("0 30"))

--"Resize Down"

local moveactivewindow = "grep -q true <<< $(hyprctl activewindow -j| jq -r . floating) && hyprctl dispatch moveactive"

hl.bind("SUPER + SHIFT + CONTROL" .. " + " .. "left", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r . floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l"))

--"Move Window Left"

hl.bind("SUPER + SHIFT + CONTROL" .. " + " .. "right", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r . floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r"))

--"Move Window Right"

hl.bind("SUPER + SHIFT + CONTROL" .. " + " .. "up", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r . floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u"))

--"Move Window Up"

hl.bind("SUPER + SHIFT + CONTROL" .. " + " .. "down", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r . floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d"))

--"Move Window Down"

hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

--"Move Window (Mouse)"

hl.bind("SUPER" .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

--"Resize Window (Mouse)"

--bind = SUPER, Z, movewindow #"Move Window (Key)"

hl.bind("SUPER" .. " + " .. "X", hl.dsp.window.resize(nil), { mouse = true })

--"Resize Window (Key)"

-- 4. Screen Capture

-- Hyprshot automatically saves and copies to clipboard by default

hl.bind("SUPER" .. " + " .. "PRINT", hl.dsp.exec_cmd("HYPRSHOT_DIR=~/Pictures/Screenshots hyprshot -m window"))

--"Screenshot-Window"

hl.bind("ALT" .. " + " .. "PRINT", hl.dsp.exec_cmd("HYPRSHOT_DIR=~/Pictures/Screenshots hyprshot -m output"))

--"Screenshot-Screen"

hl.bind("SUPER + SHIFT" .. " + " .. "PRINT", hl.dsp.exec_cmd("HYPRSHOT_DIR=~/Pictures/Screenshots hyprshot -m region"))

--"Screenshot-Region"

-- Advanced Editor

hl.bind("SUPER" .. " + " .. "A", hl.dsp.exec_cmd("grim -g $(slurp) - |  satty --filename- --output-filename ~/Pictures/Screenshots/Screenshot-$(date '+%Y%m%d-%H:%M:%S').png"))

--"Screenshot-Region w/ Editor"

-- THE ULTIMATE QUICK SCREENSHOT: Drag to select -> Auto-Saves to file AND Auto-Copies to clipboard

hl.bind("PRINT", hl.dsp.exec_cmd("HYPRSHOT_DIR=$HOME/Pictures/Screenshots hyprshot -m region"))

--"Quick Region Save & Copy"

--clipboard

hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| wofi --dmenu| cliphist decode| wl-copy"))

-- 5. Workspaces

hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

--"Workspace 1"

hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

--"Workspace 2"

hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

--"Workspace 3"

hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

--"Workspace 4"

hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

--"Workspace 5"

hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

--"Workspace 6"

hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

--"Workspace 7"

hl.bind("SUPER" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

--"Workspace 8"

hl.bind("SUPER" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

--"Workspace 9"

hl.bind("SUPER" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

--"Workspace 10"

hl.bind("SUPER + CONTROL" .. " + " .. "Right", hl.dsp.focus({ workspace = "r+1" }))

--"Next Workspace"

hl.bind("SUPER + CONTROL" .. " + " .. "Left", hl.dsp.focus({ workspace = "r-1" }))

--"Previous Workspace"

hl.bind("SUPER + CONTROL" .. " + " .. "Down", hl.dsp.focus({ workspace = "empty" }))

--"Nearest Empty Workspace"

hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

--"Scroll Workspace Forward"

hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

--"Scroll Workspace Backward"

hl.bind("SUPER + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

--"Move to Workspace 1"

hl.bind("SUPER + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

--"Move to Workspace 2"

hl.bind("SUPER + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

--"Move to Workspace 3"

hl.bind("SUPER + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

--"Move to Workspace 4"

hl.bind("SUPER + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

--"Move to Workspace 5"

hl.bind("SUPER + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

--"Move to Workspace 6"

hl.bind("SUPER + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

--"Move to Workspace 7"

hl.bind("SUPER + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

--"Move to Workspace 8"

hl.bind("SUPER + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

--"Move to Workspace 9"

hl.bind("SUPER + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

--"Move to Workspace 10"

hl.bind("SUPER + CONTROL + ALT" .. " + " .. "Right", hl.dsp.window.move({ workspace = "r+1" }))

--"Move to Next Relative Workspace"

hl.bind("SUPER + CONTROL + ALT" .. " + " .. "Left", hl.dsp.window.move({ workspace = "r-1" }))

--"Move to Previous Relative Workspace"

-- The Magic Scratchpad (Minimize/Restore)

hl.bind("SUPER" .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind("SUPER + SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- 6. HARDWARE CONTROLS

-- Volume (F1, F2, F3)

hl.bind("F1", hl.dsp.exec_cmd("pamixer -t"))

--"Mute/Unmute Speakers"

hl.bind("F2", hl.dsp.exec_cmd("pamixer -d 5"))

--"Volume Down (Holdable)"

hl.bind("F3", hl.dsp.exec_cmd("pamixer -i 5"))

--"Volume Up (Holdable)"

-- Microphone (F4)

hl.bind("F4", hl.dsp.exec_cmd("pamixer --default-source -t"))

--"Mute/Unmute Mic"

-- Brightness (Move these to whatever keys match your keyboard!)

hl.bind("F5", hl.dsp.exec_cmd("brightnessctl s 5%-"))

--"Brightness Down (Holdable)"

hl.bind("F6", hl.dsp.exec_cmd("brightnessctl s +5%"))

--"Brightness Up (Holdable)"

-- Media Playback (F6, F7, F8)

hl.bind("F6", hl.dsp.exec_cmd("playerctl previous"))

--"Previous Track"

hl.bind("F7", hl.dsp.exec_cmd("playerctl play-pause"))

--"Play/Pause"

hl.bind("F8", hl.dsp.exec_cmd("playerctl next"))

--"Next Track"

-- Keep the original XF86 keys just in case you ever hold the 'Fn' key!

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5%"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"))

-- 7. CUSTOM SYSTEM & MUSIC SHORTCUTS

-- Power Controls (Requires Super + Shift so you don't misclick!)

hl.bind("SUPER + SHIFT" .. " + " .. "Delete", hl.dsp.exec_cmd("systemctl poweroff"))

--"Instant Shutdown"

hl.bind("SUPER + SHIFT" .. " + " .. "Backspace", hl.dsp.exec_cmd("systemctl reboot"))

--"Instant Restart"

hl.bind("SUPER + SHIFT" .. " + " .. "Z", hl.dsp.exec_cmd("systemctl suspend"))

--"Sleep / Suspend"

-- Music Controls (Fast 1-handed shortcuts while coding)

hl.bind("SUPER + SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("playerctl play-pause"))

--"Play/Pause"

hl.bind("SUPER + SHIFT" .. " + " .. "Comma", hl.dsp.exec_cmd("playerctl previous"))

--"Previous Track (<)"

hl.bind("SUPER + SHIFT" .. " + " .. "Period", hl.dsp.exec_cmd("playerctl next"))

--"Next Track (>)"

--spotify

hl.bind("SUPER" .. " + " .. "M", hl.dsp.exec_cmd("spotify --enable-features=UseOzonePlatform --ozone-platform=wayland || pgrep spotify && playerctl -p spotify play-pause"))

-- Spotify Track Skipping

hl.bind("SUPER" .. " + " .. "slash", hl.dsp.exec_cmd("playerctl -p spotify next"))

--"Spotify Next Track" (Changed from period to avoid emoji conflict)

hl.bind("SUPER" .. " + " .. "comma", hl.dsp.exec_cmd("playerctl -p spotify previous"))

--"Spotify Previous Track" 

--8 keyboard

hl.bind("SUPER" .. " + " .. "semicolon", hl.dsp.exec_cmd("emote"))
