-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--SYSTEMWIDE CURSOR (Change to your theme)

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

hl.env("XCURSOR_SIZE", 24)

hl.env("QT_CURSOR_THEME", "Bibata-Modern-Classic")

hl.env("QT_CURSOR_SIZE", 24)

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 2,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(21215fff)", "rgba(21215fff)" }, angle = 45 },
            inactive_border = { colors = { "rgba(070722cc)", "rgba(070722cc)" }, angle = 45 },
        },
    },
})

hl.config({
    group = {
        col = {
            border_active = { colors = { "rgba(21215fff)", "rgba(21215fff)" }, angle = 45 },
            border_inactive = { colors = { "rgba(070722cc)", "rgba(070722cc)" }, angle = 45 },
            border_locked_active = { colors = { "rgba(21215fff)", "rgba(21215fff)" }, angle = 45 },
            border_locked_inactive = { colors = { "rgba(070722cc)", "rgba(070722cc)" }, angle = 45 },
        },
    },
})

hl.config({
    decoration = {
        rounding = 15,
        shadow = {
            enabled = true,
        },
        active_opacity = 1.0,
        inactive_opacity = 0.90,
        fullscreen_opacity = 1.0,
        blur = {
            enabled = true,
            size = 1,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            special = true,
        },
    },
})
