#INPUTS

input {
    # Keyboard: Add a layout and uncomment kb_options for Win+Space switching shortcut
    kb_layout = us
    # kb_options = grp:win_space_toggle
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35
    accel_profile = flat
    
    touchpad {
	tap-to-click = true
        natural_scroll = yes
	clickfinger_behavior = false
        scroll_factor = 0.5
    }
    special_fallthrough = true
    follow_mouse = 1
}

#gesture = 3, horizontal, workspace
#gesture = 3, pinchin,float,tile
#gesture = 3, pinchout,float, float
